name: Daily Checkin
on:
  workflow_dispatch: 
  schedule:
    - cron: '17 22 * * *' # 避开高峰期，北京时间 6:17 运行
jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests pyotp
      - name: Run script
        env:
          IKUUU_EMAIL: ${{ secrets.IKUUU_EMAIL }}
          IKUUU_PASSWORD: ${{ secrets.IKUUU_PASSWORD }}
          IKUUU_2FA_SECRET: ${{ secrets.IKUUU_2FA_SECRET }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py
